# This workflow builds and deploys a Jekyll site to GitHub Pages.
# Combines certified and non-certified actions, supports both root and /docs directory, and is compatible with modern GitHub Actions versions.

name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Only one deployment at a time. Set cancel-in-progress as appropriate.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    # Remove defaults.run.working-directory for flexibility; set working-directory in steps if needed.
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optionally detect if /docs exists for Jekyll source
      - name: Setup Ruby (if using custom plugins/Gemfile)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true 
          cache-version: 0

      - name: Install dependencies (if Gemfile present)
        if: hashFiles('Gemfile') != ''
        run: bundle install
        env:
          JEKYLL_ENV: production

      # Use either the certified Jekyll build action or manual Jekyll build depending on project structure.
      # (Comment/uncomment as needed.)

      # Certified: Handles most use cases (default . as source, _site as destination)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll (certified)
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./ # Change to './' if site source is root
          destination: ./_site

      # OR manual (uncomment if using custom Jekyll plugins or configs)
      # - name: Build with Jekyll (manual)
      #   run: bundle exec jekyll build --source ./docs --destination ./docs/_site --baseurl "${{ steps.pages.outputs.base_path }}"
      #   env:
      #     JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /_site/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
