name: List Repos
on:
  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List repositories
        run: |
          echo "Listing repositories for ${{ github.repository }}"
          gh repo list ${{ github.repository_owner }} --limit 100